//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annapurna_Tbl
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public long Visitors { get; set; }
        public long TotalVisitors { get; set; }
        public Nullable<decimal> PercentageVisitors { get; set; }
        public string Place { get; set; }
        public string PlaceName { get; set; }
        public string Place_Name { get; set; }
    }
}
