//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelTable
    {
        public int Id { get; set; }
        public string HotelName { get; set; }
        public string HotelDescription { get; set; }
        public string HotelPlace { get; set; }
        public Nullable<int> HotelRating { get; set; }
        public string HotelImage { get; set; }
        public string BedImage { get; set; }
        public string BedImage1 { get; set; }
        public string BedImage2 { get; set; }
        public string Standard { get; set; }
    }
}
