//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelInfoDatabaseEntities : DbContext
    {
        public HotelInfoDatabaseEntities()
            : base("name=HotelInfoDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HotelTable> HotelTables { get; set; }

        public System.Data.Entity.DbSet<ProjectTAMA.Models.HotelDesViewModel> HotelDesViewModels { get; set; }
    }
}
