//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceTable
    {
        public int PlaceID { get; set; }
        public string PlaceName { get; set; }
        public string PlaceDescription { get; set; }
        public byte[] PlaceImage { get; set; }
    }
}
