//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlacesInfoDatabaseEntities1 : DbContext
    {
        public PlacesInfoDatabaseEntities1()
            : base("name=PlacesInfoDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlaceDescriptionTable> PlaceDescriptionTables { get; set; }

        public System.Data.Entity.DbSet<ProjectTAMA.Models.PlaceDescriptionViewModel> PlaceDescriptionViewModels { get; set; }

      


    }
}
