//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlacesInfoDatabaseEntities2 : DbContext
    {
        public PlacesInfoDatabaseEntities2()
            : base("name=PlacesInfoDatabaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Annapurna_Tbl> Annapurna_Tbl { get; set; }
        public virtual DbSet<Everest_Tbl> Everest_Tbl { get; set; }
        public virtual DbSet<Pashupatinath_Tbl> Pashupatinath_Tbl { get; set; }
        public virtual DbSet<PlaceDescriptionTable> PlaceDescriptionTables { get; set; }
        public virtual DbSet<PlaceTable> PlaceTables { get; set; }
        public virtual DbSet<Tbl_Lumbini> Tbl_Lumbini { get; set; }
    }
}
