//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTAMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Lumbini
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public Nullable<long> Visitors { get; set; }
        public string TotalVisitor { get; set; }
        public Nullable<long> PercentageVisitor { get; set; }
    }
}
